Suppress -Wunnecessary-virtual-specifier for clang-r584948
This is to workaround the following build error when doing clang update.

external/icu/icu4c/source/common/unicode/uniset.h:498:18:
error: virtual method 'operator==' is inside a 'final' class
and can never be overridden [-Werror,-Wunnecessary-virtual-specifier]
  498 |     virtual bool operator==(const UnicodeSet& o) const;
      |                  ^

This warning has been fixed in icu upstream, can be re-enabled
after updating from upstream.

Bug: 452729455
Test: build
Change-Id: Ide4027bd35406c032629baac5fb229fcb6847828