Disable -Wunnecessary-virtual-specifier
This is to workaround the following build error when doing clang update.

external/icu/icu4c/source/common/unicode/uniset.h:498:18:
error: virtual method 'operator==' is inside a 'final' class
and can never be overridden [-Werror,-Wunnecessary-virtual-specifier]
  498 |     virtual bool operator==(const UnicodeSet& o) const;
      |                  ^

This warning has been fixed in icu upstream, can be re-enabled
after updating from upstream.

Bug: 452729455
Test: build
Change-Id: I401deac7312e06c3aca025bd170010d8d6256831